### ISSUE TITLE
it doesn't launches

### ISSUE THREAD

**Issue by bIaBlaBla** [Steve987321/toadclicker#5]
even if tried to open in administrator mode, a cmd opens and no gui appears

**Comment by Steve987321** [comment]
When opening the clicker it will try to read options.txt in the minecraft folder and check for hotbar keybinds. Sometimes this causes a crash because something unexpected is being read as a hotkey.

Will be easy to fix, so will fix soon

**Comment by Steve987321** [comment]
https://github.com/Steve987321/toadclicker/releases/tag/v1.7.6
