### ISSUE TITLE
Doesn't work on bedrock edition

### ISSUE THREAD

**Issue by ytcyde** [Steve987321/toadclicker#8]

**Comment by ytcyde** [comment]
or maybe because it is because im on windows 11

**Comment by Steve987321** [comment]
If you want to make the autoclicker work on other applications you have to adjust your settings (this is for Version 1.7.7): 

Go to misc and **toggle on use mouse_event** (uses another winapi function to send clicks) 
Also **select your clicking window** in the custom window tab, Active window or Custom Window. 
Go to clicker and **toggle on when mouse visible**.

Now there are currenlty limits to what binds you can use to autoclick. So before when you press left mouse button you autoclick now you need to rebind it to something else. 

In the clicker tab (to the right of the enable checkbox) bind a key you want to use to autoclick, then under it there are now 2 modes you can use to autoclick:
- Hold to Click: When holding the bind key it autoclicks
- Toggle to Click: When pressing the bind key it toggles the clicker and autoclicks when it is enabled.

This will hopefully be more convenient to configure on later versions.

**Comment by ytcyde** [comment]
This worked.
